Update euse to look for /etc/portage/make.conf as well as /etc/make.conf. Bug 346519
svn path=/trunk/gentoolkit/; revision=866

diff --git a/bin/euse b/bin/euse
--- a/bin/euse
+++ b/bin/euse
@@ -9,7 +9,20 @@
 PROGRAM_NAME=euse
 VERSION="svn"
 
-MAKE_CONF_PATH=/etc/make.conf
+error() {
+	echo "ERROR: ${1}"
+	set +f
+	exit 1
+}
+
+# Portage now supports make.conf in /etc and /etc/portage
+if [ -r /etc/make.conf ]; then
+	MAKE_CONF_PATH=/etc/make.conf
+elif [ -r /etc/portage/make.conf ]; then
+	MAKE_CONF_PATH=/etc/portage/make.conf
+else
+	error "make.conf file is not readable"
+fi
 MAKE_GLOBALS_PATH=/etc/make.globals
 MAKE_PROFILE_PATH=/etc/make.profile
 MAKE_CONF_BACKUP_PATH=/etc/make.conf.euse_backup
@@ -47,12 +60,6 @@ parse_arguments() {
 		esac
 		shift
 	done
-}
-
-error() {
-	echo "ERROR: ${1}"
-	set +f
-	exit 1
 }
 
 get_real_path() {
