Fix eread to not accept invalid input for file selection. (Bug #189994)
svn path=/; revision=436

diff --git a/trunk/src/eread/eread b/trunk/src/eread/eread
--- a/trunk/src/eread/eread
+++ b/trunk/src/eread/eread
@@ -49,31 +49,36 @@ select_loop() {
 				break
 				;;
 			*)
-				${PAGER} ${FILE}
-				read -p "Delete file? [y/N] " DELETE
-				case ${DELETE} in
-					q)
-						echo "Quitting"
-						QUIT="yes"
-						break
-						;;
-					y|Y)
-						rm -f ${FILE}
-						SUCCESS=$?
-						if [[ ${SUCCESS} = 0 ]]; then
-							echo "Deleted ${FILE}"
-						else
-							echo "Unable to delete ${FILE}"
-						fi
-						;;
-					# Empty string defaults to N (save file)
-					n|N|"")
-						echo "Saving ${FILE}"
-						;;
-					*)
-						echo "Invalid response. Saving ${FILE}"
-						;;
-				esac
+				if [ -f "$FILE" ]; then
+					${PAGER} ${FILE}
+					read -p "Delete file? [y/N] " DELETE
+					case ${DELETE} in
+						q)
+							echo "Quitting"
+							QUIT="yes"
+							break
+							;;
+						y|Y)
+							rm -f ${FILE}
+							SUCCESS=$?
+							if [[ ${SUCCESS} = 0 ]]; then
+								echo "Deleted ${FILE}"
+							else
+								echo "Unable to delete ${FILE}"
+							fi
+							;;
+						# Empty string defaults to N (save file)
+						n|N|"")
+							echo "Saving ${FILE}"
+							;;
+						*)
+							echo "Invalid response. Saving ${FILE}"
+							;;
+					esac
+				else
+					echo
+					echo "Invalid response."
+				fi
 				;;
 		esac
 		break
