Check for permissions to write temporary files. Bug #142308
svn path=/; revision=313

diff --git a/trunk/src/revdep-rebuild/revdep-rebuild b/trunk/src/revdep-rebuild/revdep-rebuild
--- a/trunk/src/revdep-rebuild/revdep-rebuild
+++ b/trunk/src/revdep-rebuild/revdep-rebuild
@@ -135,7 +135,25 @@ done
 NOCOLOR=$(portageq envvar NOCOLOR)
 
 # Base of temporary files names.
-LIST=~/.revdep-rebuild
+touch ${HOME}/.revdep-rebuild_0.test 2>/dev/null
+if [ $? -eq 0 ]
+then
+	LIST="${HOME}/.revdep-rebuild"
+	rm ~/.revdep-rebuild_0.test
+else
+	# Try to use /var/tmp since $HOME is not available
+	touch /var/tmp/.revdep-rebuild_0.test 2>/dev/null
+	if [ $? -eq 0 ]
+	then
+		LIST="/var/tmp/.revdep-rebuild"
+		rm /var/tmp/.revdep-rebuild_0.test
+	else
+		echo
+		echo "!!! Unable to write temporary files to either $HOME or /var/tmp !!!"
+		echo
+		exit 1
+	fi
+fi
 
 shopt -s nullglob
 shopt -s expand_aliases
